# Generated by Django 5.0.3 on 2024-04-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio',
            field=models.FileField(default=None, null=True ,upload_to='audio_files/'),
        ),
    ]
