# Generated by Django 5.0.3 on 2024-04-09 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_audio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio',
        ),
    ]
