# Generated by Django 5.0.3 on 2024-04-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_userloginlogout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default='/WhatsApp Image 2024-04-09 at 3.38.05 PM.jpeg', upload_to='profile_images/'),
        ),
    ]
