# Generated by Django 3.2.24 on 2024-02-15 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_content',
            field=models.FileField(default=None, max_length=200, upload_to='Video/'),
        ),
        migrations.AddField(
            model_name='post',
            name='thumbnails',
            field=models.FileField(default=None, max_length=300, upload_to='thumbnails/'),
        ),
    ]
