# Generated by Django 3.2.24 on 2024-02-15 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240215_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_content',
            field=models.FileField(default=None, max_length=200, null=True, upload_to='Video/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnails',
            field=models.FileField(default=None, max_length=300, null=True, upload_to='thumbnails/'),
        ),
    ]
