# Generated by Django 5.0.2 on 2024-02-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnails',
            field=models.ImageField(blank=True, default=None, upload_to='.uploads/'),
        ),
    ]
