# Generated by Django 5.0.2 on 2024-02-15 09:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240215_1219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='faetured_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='featured_image/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
