# Generated by Django 5.0.2 on 2024-02-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_thumbnails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnails',
            field=models.ImageField(default=None, upload_to='thumbnails/'),
        ),
    ]
