# Generated by Django 5.0.2 on 2024-02-17 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
    ]
