# Generated by Django 5.0.2 on 2024-02-17 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_description_user_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
