# Generated by Django 5.0.2 on 2024-02-19 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_user_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
    ]
