# Generated by Django 5.0.2 on 2024-02-19 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, choices=[('CN', 'China'), ('IN', 'India'), ('US', 'United States'), ('ID', 'Indonesia'), ('PK', 'Pakistan'), ('BR', 'Brazil'), ('NG', 'Nigeria'), ('BD', 'Bangladesh'), ('RU', 'Russia'), ('MX', 'Mexico'), ('JP', 'Japan'), ('ET', 'Ethiopia'), ('PH', 'Philippines'), ('EG', 'Egypt'), ('VN', 'Vietnam'), ('CD', 'Democratic Republic of the Congo'), ('TR', 'Turkey'), ('IR', 'Iran'), ('DE', 'Germany'), ('TH', 'Thailand'), ('GB', 'United Kingdom'), ('FR', 'France'), ('IT', 'Italy'), ('TZ', 'Tanzania'), ('ZA', 'South Africa'), ('KR', 'South Korea'), ('CO', 'Colombia'), ('KE', 'Kenya'), ('AR', 'Argentina'), ('UA', 'Ukraine'), ('SD', 'Sudan'), ('PL', 'Poland'), ('DZ', 'Algeria'), ('CA', 'Canada'), ('UG', 'Uganda'), ('MA', 'Morocco'), ('PE', 'Peru'), ('IQ', 'Iraq'), ('SA', 'Saudi Arabia'), ('UZ', 'Uzbekistan'), ('MY', 'Malaysia'), ('VE', 'Venezuela'), ('AF', 'Afghanistan'), ('GH', 'Ghana'), ('NP', 'Nepal'), ('YE', 'Yemen'), ('KP', 'North Korea'), ('MG', 'Madagascar'), ('CM', 'Cameroon'), ('CI', 'Ivory Coast'), ('AU', 'Australia'), ('NE', 'Niger'), ('TW', 'Taiwan'), ('LK', 'Sri Lanka'), ('BF', 'Burkina Faso'), ('ML', 'Mali'), ('RO', 'Romania'), ('MW', 'Malawi'), ('CL', 'Chile'), ('KZ', 'Kazakhstan'), ('ZM', 'Zambia'), ('GT', 'Guatemala'), ('EC', 'Ecuador'), ('SY', 'Syria'), ('NL', 'Netherlands'), ('SN', 'Senegal'), ('KP', 'Cambodia'), ('TD', 'Chad'), ('SO', 'Somalia'), ('ZW', 'Zimbabwe'), ('RW', 'Rwanda'), ('GN', 'Guinea'), ('BJ', 'Benin'), ('TN', 'Tunisia'), ('BE', 'Belgium'), ('CU', 'Cuba'), ('BO', 'Bolivia'), ('HT', 'Haiti'), ('GR', 'Greece'), ('DO', 'Dominican Republic'), ('CZ', 'Czech Republic'), ('PT', 'Portugal'), ('SV', 'El Salvador'), ('HN', 'Honduras')], default='IN', max_length=2),
        ),
    ]
