# Generated by Django 5.0.2 on 2024-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_user_gender_alter_user_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=None, height_field='40px', upload_to='profile_images/', width_field='40px'),
        ),
    ]
