# Generated by Django 5.0.2 on 2024-02-20 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_replycomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReplyComment',
        ),
    ]
