# Generated by Django 5.0.2 on 2024-02-22 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tag',
            new_name='tags',
        ),
    ]
