# Generated by Django 3.2.24 on 2024-02-13 12:33

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_text_slug',
            field=autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='question_text', unique=True),
        ),
    ]
